# calendar_service.py - export deadlines to .ics and import .ics schedules

from datetime import datetime, timedelta
from icalendar import Calendar, Event, vRecur
from dateutil.rrule import rrulestr
from dateutil import tz
import re
from typing import Optional

def generate_ics(
    deadlines: list[dict],
    course_code: str = "Course",
    course_name: str = "",
) -> bytes:
    cal = Calendar()
    cal.add("prodid", "-//Syllabus Helper//EN")
    cal.add("version", "2.0")
    cal.add("calscale", "GREGORIAN")
    cal.add("x-wr-calname", f"{course_code} Deadlines")

    for dl in deadlines:
        if not dl.get("date"):
            continue

        event = Event()

        # Summary
        summary = f"{course_code} - {_clean_description(dl['description'], dl['type'])}"
        event.add("summary", summary)

        # Date
        dt = datetime.strptime(dl["date"], "%Y-%m-%d")
        event.add("dtstart", dt.date())
        event.add("dtend", dt.date())

        # Description with context
        desc_parts = []
        if course_name:
            desc_parts.append(f"Course: {course_code} - {course_name}")
        desc_parts.append(f"Type: {dl['type'].replace('_', ' ').title()}")
        if dl.get("context"):
            desc_parts.append(f"Context: {dl['context']}")
        desc_parts.append("\nGenerated by Syllabus Helper")
        event.add("description", "\n".join(desc_parts))

        # Color/category based on type
        event.add("categories", [_type_to_category(dl["type"])])

        # Reminders: 1 week before + 1 day before
        from icalendar import Alarm
        for minutes in [10080, 1440]:  # 7 days, 1 day
            alarm = Alarm()
            alarm.add("action", "DISPLAY")
            alarm.add("description", f"Reminder: {summary}")
            alarm.add("trigger", timedelta(minutes=-minutes))
            event.add_component(alarm)

        # Unique ID
        uid = f"{course_code}-{dl['date']}-{dl['type']}@syllabushelper"
        event.add("uid", uid)
        event.add("dtstamp", datetime.now())

        cal.add_component(event)

    return cal.to_ical()


def _clean_description(desc: str, event_type: str) -> str:
    labels = {
        "midterm": "Midterm Exam",
        "final_exam": "Final Exam",
        "presentation": "Capstone Presentation",
        "project": "Project Due",
        "homework": "Homework Due",
        "quiz": "Quiz",
        "deadline": "Deadline",
    }
    return labels.get(event_type, desc[:60])


def _type_to_category(event_type: str) -> str:
    categories = {
        "midterm": "Exam",
        "final_exam": "Exam",
        "quiz": "Exam",
        "project": "Assignment",
        "homework": "Assignment",
        "presentation": "Presentation",
        "deadline": "Assignment",
    }
    return categories.get(event_type, "Academic")


def _sanitize_ics(ics_bytes: bytes) -> bytes:
    # fix malformed .ics files (USC exports sometimes have broken lines)
    text = ics_bytes.decode("utf-8", errors="replace")
    clean_lines = []
    for line in text.splitlines():
        # Skip lines that are clearly broken (no colon, not a continuation line)
        stripped = line.strip()
        if not stripped:
            continue
        # Valid ICS lines either start with a space/tab (continuation) or contain a colon/semicolon
        if stripped[0] in (" ", "\t"):
            clean_lines.append(line)  # continuation line
        elif ":" in stripped or ";" in stripped:
            clean_lines.append(line)  # normal property line
        elif stripped in ("BEGIN:VCALENDAR", "END:VCALENDAR", "BEGIN:VEVENT",
                          "END:VEVENT", "BEGIN:VALARM", "END:VALARM",
                          "BEGIN:VTIMEZONE", "END:VTIMEZONE", "BEGIN:STANDARD",
                          "END:STANDARD", "BEGIN:DAYLIGHT", "END:DAYLIGHT"):
            clean_lines.append(line)
        # else: skip malformed line
    return "\r\n".join(clean_lines).encode("utf-8")


def parse_ics(ics_bytes: bytes) -> dict:
    ics_bytes = _sanitize_ics(ics_bytes)
    cal = Calendar.from_ical(ics_bytes)

    events_raw = []
    for component in cal.walk():
        if component.name != "VEVENT":
            continue

        summary = str(component.get("summary", ""))
        dtstart = component.get("dtstart")
        dtend = component.get("dtend")
        location = str(component.get("location", ""))
        description = str(component.get("description", ""))
        rrule = component.get("rrule")

        if not dtstart:
            continue

        start = dtstart.dt
        end = dtend.dt if dtend else None

        # Handle recurring events (weekly class sessions)
        recurrences = []
        if rrule:
            rrule_str = rrule.to_ical().decode("utf-8")
            try:
                rule = rrulestr(rrule_str, dtstart=start)
                # Get occurrences for the semester (max 20 weeks)
                until = start + timedelta(weeks=20)
                recurrences = list(rule.between(start, until, inc=True))
            except Exception:
                recurrences = [start]
        else:
            recurrences = [start]

        events_raw.append({
            "summary": summary,
            "start": start,
            "end": end,
            "location": location,
            "description": description,
            "recurrences": recurrences,
            "is_recurring": rrule is not None,
        })

    # Group by course
    courses = _group_into_courses(events_raw)
    # Build semester overview
    all_events = _flatten_events(events_raw)

    return {
        "courses": courses,
        "total_events": len(all_events),
        "all_events": all_events,
    }


def _group_into_courses(events: list[dict]) -> list[dict]:
    # group events by course code extracted from the event summary
    course_map: dict[str, dict] = {}

    for ev in events:
        summary = ev["summary"]
        course_key = _extract_course_key(summary)

        if course_key not in course_map:
            course_map[course_key] = {
                "course_code": course_key,
                "course_name": _extract_course_name(summary, course_key),
                "location": ev["location"],
                "sessions": [],
                "is_recurring": ev["is_recurring"],
            }

        # Add session info
        start = ev["start"]
        end = ev["end"]
        if hasattr(start, "strftime"):
            day_of_week = start.strftime("%A")
            start_time = start.strftime("%I:%M %p") if hasattr(start, "hour") else "All day"
            end_time = end.strftime("%I:%M %p") if end and hasattr(end, "hour") else ""
        else:
            day_of_week = start.strftime("%A") if hasattr(start, "strftime") else "Unknown"
            start_time = "All day"
            end_time = ""

        session = {
            "day": day_of_week,
            "start_time": start_time,
            "end_time": end_time,
            "date": start.isoformat() if hasattr(start, "isoformat") else str(start),
            "location": ev["location"],
        }

        # Avoid duplicate sessions (same day/time)
        session_key = f"{day_of_week}-{start_time}"
        if not any(f"{s['day']}-{s['start_time']}" == session_key for s in course_map[course_key]["sessions"]):
            course_map[course_key]["sessions"].append(session)

        # Count total occurrences
        course_map[course_key].setdefault("total_occurrences", 0)
        course_map[course_key]["total_occurrences"] += len(ev["recurrences"])

    return list(course_map.values())


def _extract_course_key(summary: str) -> str:
    m = re.search(r"([A-Z]{2,5})\s*[-]?\s*(\d{3}[A-Z]?)", summary.upper())
    if m:
        return f"{m.group(1)} {m.group(2)}"
    # Fallback: use first meaningful words
    clean = re.sub(r"[^A-Za-z0-9\s]", "", summary).strip()
    return clean[:30] if clean else "Unknown Course"


def _extract_course_name(summary: str, code: str) -> str:
    name = re.sub(re.escape(code.replace(" ", r"\s*")), "", summary, flags=re.I).strip()
    name = re.sub(r"^[\s\-–:]+", "", name).strip()
    return name if name else code


def _flatten_events(events: list[dict]) -> list[dict]:
    flat = []
    for ev in events:
        for dt in ev["recurrences"][:30]:  # Cap at 30 occurrences
            flat.append({
                "summary": ev["summary"],
                "date": dt.isoformat() if hasattr(dt, "isoformat") else str(dt),
                "location": ev["location"],
            })
    flat.sort(key=lambda x: x["date"])
    return flat
